export const blogPosts = [
  {
    id: 7,
    slug: "write-cv-gets-noticed-2026",
    title: "How to Write a CV That Gets Noticed in 2026",
    excerpt:
      "Recruiters skim a CV in seconds. Learn the structure, phrasing, and details that make yours impossible to ignore — and land more interviews in 2026.",
    author: "Resumate Team",
    readTime: "8 min read",
    date: "Aug 10, 2026",
    category: "Career Advice",
    image: "/blog/cover-write-cv-gets-noticed-2026.svg",
  },
  {
    id: 8,
    slug: "what-recruiters-look-for-cv",
    title: "What Recruiters Actually Look for in a CV",
    excerpt:
      "What really moves the needle when a recruiter reviews your CV? We asked hiring experts — here's what they scan for first and how to deliver it.",
    author: "Resumate Team",
    readTime: "6 min read",
    date: "Jul 28, 2026",
    category: "Career Advice",
    image: "/blog/cover-what-recruiters-look-for-cv.svg",
  },
  {
    id: 9,
    slug: "cv-vs-resume-difference",
    title: "CV vs Resume: What's the Difference?",
    excerpt:
      "CV or resume? They're not the same document. Understand the differences, when to use each one, and how to format yours for the role you want.",
    author: "Resumate Team",
    readTime: "5 min read",
    date: "Jul 15, 2026",
    category: "Tips",
    image: "/blog/cover-cv-vs-resume-difference.svg",
  },
  {
    id: 10,
    slug: "highlight-skills-no-experience",
    title: "How to Highlight Your Skills With No Experience",
    excerpt:
      "No work history yet? You still have skills worth showing. Turn projects, education, and volunteer work into a CV that opens doors.",
    author: "Resumate Team",
    readTime: "7 min read",
    date: "Jun 30, 2026",
    category: "Tips",
    image: "/blog/cover-highlight-skills-no-experience.svg",
  },
  {
    id: 11,
    slug: "write-strong-professional-summary",
    title: "How to Write a Strong Professional Summary",
    excerpt:
      "Your professional summary is the first thing recruiters read. Write one that sells your experience in three or four punchy, keyword-rich lines.",
    author: "Resumate Team",
    readTime: "6 min read",
    date: "Jun 18, 2026",
    category: "Tips",
    image: "/blog/cover-write-strong-professional-summary.svg",
  },
  {
    id: 1,
    slug: "ats-friendly-resume-2026",
    title: "How to Build an ATS-Friendly Resume in 2026",
    excerpt:
      "Over 75% of resumes are rejected by applicant tracking systems before a human ever reads them. Here's how to make sure yours gets through.",
    author: "Resumate Team",
    readTime: "5 min read",
    date: "Feb 12, 2026",
    category: "ATS",
    featured: true,
    image: "/blog/cover-ats-friendly-resume-2026.svg",
  },
  {
    id: 2,
    slug: "top-resume-templates-tech",
    title: "Top Resume Templates for Tech Professionals",
    excerpt:
      "Tech hiring managers spend an average of 6 seconds scanning a resume. Pick a template that presents your experience clearly.",
    author: "Resumate Team",
    readTime: "4 min read",
    date: "Jan 28, 2026",
    category: "Templates",
    image: "/blog/cover-top-resume-templates-tech.svg",
  },
  {
    id: 3,
    slug: "ai-resume-writing",
    title: "How AI Is Revolutionizing Resume Writing",
    excerpt:
      "AI resume builders analyze thousands of successful resumes to help you craft content that stands out. Here's how to use them well.",
    author: "Resumate Team",
    readTime: "6 min read",
    date: "Jan 15, 2026",
    category: "AI",
    image: "/blog/cover-ai-resume-writing.svg",
  },
  {
    id: 4,
    slug: "common-resume-mistakes",
    title: "10 Common Resume Mistakes and How to Avoid Them",
    excerpt:
      "Even the most qualified candidates can undermine their chances with preventable mistakes. Avoid these pitfalls to stand out.",
    author: "Resumate Team",
    readTime: "5 min read",
    date: "Dec 30, 2025",
    category: "Tips",
    image: "/blog/cover-common-resume-mistakes.svg",
  },
  {
    id: 5,
    slug: "tailor-resume-industries",
    title: "How to Tailor Your Resume for Any Industry",
    excerpt:
      "One size doesn't fit all. Customize your resume for tech, finance, creative, and healthcare roles with these strategies.",
    author: "Resumate Team",
    readTime: "7 min read",
    date: "Dec 12, 2025",
    category: "Career Advice",
    image: "/blog/cover-tailor-resume-industries.svg",
  },
  {
    id: 6,
    slug: "cover-letter-best-practices",
    title: "Cover Letter Best Practices That Get You Interviews",
    excerpt:
      "A well-crafted cover letter can be the difference between an interview and a rejection. Write one that gets results.",
    author: "Resumate Team",
    readTime: "5 min read",
    date: "Nov 24, 2025",
    category: "Cover Letters",
    image: "/blog/cover-cover-letter-best-practices.svg",
  },
];

export const blogCategories = [
  "All",
  ...Array.from(new Set(blogPosts.map((p) => p.category))),
];
